#!/usr/bin/env bash
# Date: 2016-03-08
# Function: Look over the Memory usage
# Maintainer: YtRen <rytubuntulinux@gmail.com>

#if [ $1 == '' ]
#then
#	free | egrep 'Mem' | awk '{print ($3-$6-$7)*100/$2 "%"}'
#else
#	free | egrep 'Mem' | awk '{print ($3)*100/$2 "%"}'
#fi

real=''
h=''
while getopts "erh" opt
do
	case $opt in
		e)
			real='False'
			;;
		r)
			real='True'
			;;
		h)
			h='True'	
			;;
		\?)
			;;
	esac
done

if [ "$h" == "True" ]
then
	echo -e "\n\e[1mOptions:\e[0m\n"
	echo -e "    \e[1m-h\e[0m"
	echo -e "       Show help"
	echo -e "    \e[1m-e\e[0m"
	echo -e "       Don't include Buffer and Cache when calculate Memory Usage(Default)"
	echo -e "    \e[1m-r\e[0m"
	echo -e "       Include Buffer and Cache when calculate Memory Usage\n"
	exit 1
fi

if [ "$real" == "True" ]
then
	free | egrep 'Mem' | awk '{print ($3)*100/$2 "%"}'
else
	free | egrep 'Mem' | awk '{print ($3-$6-$7)*100/$2 "%"}'
fi
